POST http://localhost:3001/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJtYW4iLCJpZCI6eyJfaWQiOiI2MWJkNmIxMmYzNDIwMWRmOTJkOTViNmIiLCJuYW1lIjoiQXJtYW4iLCJlbWFpbCI6ImFybWFuaGFydXQ5OEBnbWFpbC5jb20iLCJwYXNzd29yZEhhc2giOiIkMmIkMTAkZXZ4LzFGLlZiQ1A3RnV5Q0ZRLll3LmVyNG5pZ2FoLjhvZ2R2TDBLQy4vMFBwZ3lKT2h3dHkiLCJwcm9qZWN0cyI6W10sIl9fdiI6MH0sImlhdCI6MTYzOTgwNDg1N30.A9U67rZgWtsJfslIhW-oycoTrN-BACG9d2KkJUGGskg

{
    "name": "test-project"
}

###
GET http://localhost:3001/projects/61bf523cac5e5504bedc567d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJtYW4iLCJpZCI6eyJfaWQiOiI2MWJmNTIzNWFjNWU1NTA0YmVkYzU2NzciLCJuYW1lIjoiQXJtYW4iLCJlbWFpbCI6ImFybWFuLmhhcnV0eXVueWFuNDIxMTdAZ21haWwuY29tIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJHFhTThrQ1FLaE1tclMxdndxZEVrSS42cHZmNWpPVm8yaVMvWWxWR2hNQUYxbkFHWHdiZ1lTIiwicHJvamVjdHMiOlt7Il9pZCI6IjYxYmY1MjNjYWM1ZTU1MDRiZWRjNTY3ZCIsIm5hbWUiOiJ0ZXN0MSIsImNyZWF0ZWQiOiJTdW4gRGVjIDE5IDIwMjEifSx7Il9pZCI6IjYxYmY1MjNlYWM1ZTU1MDRiZWRjNTY4MiIsIm5hbWUiOiJ0ZXN0MiIsImNyZWF0ZWQiOiJTdW4gRGVjIDE5IDIwMjEifSx7Il9pZCI6IjYxYmY1MjQwYWM1ZTU1MDRiZWRjNTY4NyIsIm5hbWUiOiJ0ZXN0MyIsImNyZWF0ZWQiOiJTdW4gRGVjIDE5IDIwMjEifV0sIl9fdiI6MH0sImlhdCI6MTYzOTkyODkwOH0.to8mej2-LSLZFNNH8TW1T3fkiXs-zwH3vvyGuOqz3B0

###
PUT http://localhost:3001/projects/61bf523cac5e5504bedc567d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJtYW4iLCJpZCI6eyJfaWQiOiI2MWJmNTIzNWFjNWU1NTA0YmVkYzU2NzciLCJuYW1lIjoiQXJtYW4iLCJlbWFpbCI6ImFybWFuLmhhcnV0eXVueWFuNDIxMTdAZ21haWwuY29tIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJHFhTThrQ1FLaE1tclMxdndxZEVrSS42cHZmNWpPVm8yaVMvWWxWR2hNQUYxbkFHWHdiZ1lTIiwicHJvamVjdHMiOlt7Il9pZCI6IjYxYmY1MjNjYWM1ZTU1MDRiZWRjNTY3ZCIsIm5hbWUiOiJ1cGRhdGVkIG5hbWUiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn0seyJfaWQiOiI2MWJmNTIzZWFjNWU1NTA0YmVkYzU2ODIiLCJuYW1lIjoidGVzdDIiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn0seyJfaWQiOiI2MWJmNTI0MGFjNWU1NTA0YmVkYzU2ODciLCJuYW1lIjoidGVzdDMiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn1dLCJfX3YiOjB9LCJpYXQiOjE2Mzk5MzI1Mjd9.WVxl8JpDbe8Q7bmiT8xXZzurFrq2jNdghW-VmxrRWOY

{
    "newName": "updated name"
}

###`
DELETE http://localhost:3001/projects/61bf523cac5e5504bedc567d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJtYW4iLCJpZCI6eyJfaWQiOiI2MWJmNTIzNWFjNWU1NTA0YmVkYzU2NzciLCJuYW1lIjoiQXJtYW4iLCJlbWFpbCI6ImFybWFuLmhhcnV0eXVueWFuNDIxMTdAZ21haWwuY29tIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJHFhTThrQ1FLaE1tclMxdndxZEVrSS42cHZmNWpPVm8yaVMvWWxWR2hNQUYxbkFHWHdiZ1lTIiwicHJvamVjdHMiOlt7Il9pZCI6IjYxYmY1MjNjYWM1ZTU1MDRiZWRjNTY3ZCIsIm5hbWUiOiJ1cGRhdGVkIG5hbWUiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn0seyJfaWQiOiI2MWJmNTIzZWFjNWU1NTA0YmVkYzU2ODIiLCJuYW1lIjoidGVzdDIiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn0seyJfaWQiOiI2MWJmNTI0MGFjNWU1NTA0YmVkYzU2ODciLCJuYW1lIjoidGVzdDMiLCJjcmVhdGVkIjoiU3VuIERlYyAxOSAyMDIxIn1dLCJfX3YiOjB9LCJpYXQiOjE2Mzk5MzMwMTh9.A2TAmTwBKodljEWKlrcePirfr22IfKa6SoqQgVhT1CE
